services:
  postgres:
    image: postgres:alpine
    container_name: "hack-u"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "DB"
    volumes:  
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  postgres-data:
